version: '3'
services:
  test_system:
    build:
      context: core/test_system/
      dockerfile: Dockerfile
    hostname: test_system
    ports:
      - "9090:9090"
    depends_on:
      - mongo
      - postgres
    environment:
      - MONGO_URI=mongodb://db:27017/
      - POSTGRES_URI=postgresql://postgres:password@postgres/mydb
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: code_versus
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  redis:
    image: redis:latest
    hostname: redis
    networks:
      - mynetwork
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api
    command: python /api/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core/api/CodeVersusAPI:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    links:
      - redis
    networks:
      - mynetwork
  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A CodeVersusAPI worker --loglevel=info
    volumes:
      - ./core/api/CodeVersusAPI:/code
    networks:
      - mynetwork
    depends_on:
      - redis

networks:
  mynetwork: