# Generated by Django 4.2.2 on 2023-07-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок задачи')),
                ('description', models.TextField(max_length=4096, verbose_name='Описание задачи')),
                ('level', models.CharField(max_length=256, verbose_name='Уровень задачи(ex Easy, Medium, Hard)')),
                ('time_complexity', models.IntegerField(verbose_name='Временной предел выполнения задачи')),
                ('space_complexity', models.IntegerField(verbose_name='Предел по памяти выполнения задачи')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
