# Generated by Django 4.2.2 on 2023-07-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_test_task_remove_test_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_service_id',
        ),
        migrations.AlterField(
            model_name='test',
            name='details',
            field=models.CharField(default='ok', verbose_name='Описание выполнения теста'),
        ),
    ]
