# Generated by Django 4.2.2 on 2023-07-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_test_test_service_id_alter_test_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='space_complexity',
            field=models.FloatField(verbose_name='Предел по памяти выполнения задачи'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_complexity',
            field=models.FloatField(verbose_name='Временной предел выполнения задачи'),
        ),
    ]
