# Generated by Django 4.2.2 on 2023-07-09 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_test_space_complexity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='task_group',
            new_name='test_group',
        ),
    ]
