# Generated by Django 4.2.2 on 2023-07-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='title',
            field=models.CharField(max_length=4096, verbose_name='Заголовок ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=4096, verbose_name='Заголовок вопроса'),
        ),
    ]
