# Generated by Django 4.2.2 on 2023-07-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='count_submit_task',
            field=models.IntegerField(default=0, verbose_name='Количество выполненных заданий'),
        ),
    ]
