# Generated by Django 4.2.2 on 2023-07-15 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_count_submit_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
