# Generated by Django 4.2.2 on 2023-07-15 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_activate_registrationcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationCode',
            new_name='VerificationCode',
        ),
    ]
