# Generated by Django 4.2.2 on 2023-07-23 16:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_registrationcode_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='code_type',
            field=models.CharField(choices=[('REGISTRATION', 'registartion'), ('RESET', 'reset')], default=users.models.VerificationCodeType['REGISTRATION'], max_length=256),
        ),
    ]
